openapi: 3.0.0
info:
  title: API de JSONPlaceholder
  description: Documentación para la API falsa de JSONPlaceholder. Hecho para el examen.
  version: 1.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/escuelapolitcnicanac/documentacion-api/1.0.0
  - url: https://jsonplaceholder.typicode.com
paths:
  /posts:
    get:
      summary: Obtener todos los posts
      operationId: getPosts
      responses:
        '200':
          description: Éxito. Devuelve una lista de posts.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
  /users:
    get:
      summary: Obtener la lista de todos los usuarios
      operationId: getUsers
      responses:
        '200':
          description: Éxito. Devuelve un arreglo de usuarios.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /comments:
    get:
      summary: Obtener la lista de todos los comentarios
      operationId: getComments
      responses:
        '200':
          description: Éxito. Devuelve un arreglo de comentarios.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
  /albums:
    get:
      summary: Obtener la lista de todos los álbumes
      operationId: getAlbums
      responses:
        '200':
          description: Éxito. Devuelve un arreglo de álbumes.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Album'
components:
  schemas:
    Post:
      type: object
      properties:
        userId:
          type: integer
          example: 1
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "sunt aut facere repellat provident occaecati excepturi optio reprehenderit"
        body:
          type: string
          example: "quia et suscipit..."
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Leanne Graham"
        username:
          type: string
          example: "Bret"
        email:
          type: string
          example: "Sincere@april.biz"
        address:
          $ref: '#/components/schemas/Address'
        phone:
          type: string
          example: "1-770-736-8031 x56442"
        website:
          type: string
          example: "hildegard.org"
        company:
          $ref: '#/components/schemas/Company'
    Comment:
      type: object
      properties:
        id:
          type: integer
          example: 1
        postId:
          type: integer
          example: 1
        name:
          type: string
          example: "id labore ex et quam laborum"
        email:
          type: string
          example: "Eliseo@gardner.biz"
        body:
          type: string
          example: "laudantium enim quasi est..."
    Album:
      type: object
      properties:
        userId:
          type: integer
          example: 1
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "quidem molestiae enim"
    Address:
      type: object
      properties:
        street:
          type: string
          example: "Kulas Light"
        suite:
          type: string
          example: "Apt. 556"
        city:
          type: string
          example: "Gwenborough"
        zipcode:
          type: string
          example: "92998-3874"
        geo:
          $ref: '#/components/schemas/Geo'
    Geo:
      type: object
      properties:
        lat:
          type: string
          example: "-37.3159"
        lng:
          type: string
          example: "81.1496"
    Company:
      type: object
      properties:
        name:
          type: string
          example: "Romaguera-Crona"
        catchPhrase:
          type: string
          example: "Multi-layered client-server neural-net"
        bs:
          type: string
          example: "harness real-time e-markets"